"""
Publish a curated Lance table as a HuggingFace Lance-format dataset.

Mirrors the layout used by ``lance-format/lerobot_xvla-soft-fold``:

    <repo>/
      data/
        train.lance/   ← the entire .lance directory uploaded as-is
      README.md        ← dataset card

After upload, readers can train against your curated subset with one
line:

    from lance_ray import read_lance
    ds = read_lance(
        "hf://datasets/<your-org>/<repo>/data/train.lance",
        columns=["index"],
    )

Pre-tokenised columns (``t5_hidden_states``, ``vae_latent``) ride along
in the same Lance dataset, so the dataloader doesn't need anything else.

Usage
-----
# Dry run — prints what would be uploaded
python -m videogen.upload_to_hf \\
    --db data/videos/lancedb \\
    --table phase_transitions_curated_train \\
    --repo my-org/wan22-phase-transitions-25k \\
    --dry-run

# Real upload (needs `huggingface-cli login` first)
python -m videogen.upload_to_hf \\
    --db data/videos/lancedb \\
    --table phase_transitions_curated_train \\
    --repo my-org/wan22-phase-transitions-25k \\
    --private
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


_README_TEMPLATE = """---
license: cc-by-4.0
language:
- en
tags:
- video
- text-to-video
- lance
- wan2.2
size_categories:
- 1K<n<10K
---

# {repo}

Lance-format video-text dataset for fine-tuning **Wan2.2-TI2V-5B** on
time-lapse phase transitions.

Generated by [`lancedb/training`](https://github.com/lancedb/training)
on the `videogen` branch.

## What's inside

- One Lance table at `data/{table}.lance/` containing `{rows}` clips.
- Pre-encoded Wan2.2-VAE latents and UMT5-XXL hidden states are stored
  as `vae_latent` (`fixed_size_list<float16>[842400]`) and
  `t5_hidden_states` (`fixed_size_list<float16>[2097152]`) columns
  respectively, so the training loop does NOT need to load the VAE or
  text encoder.

## Quick start

```python
from lance_ray import read_lance

ds = read_lance("hf://datasets/{repo}/data/{table}.lance",
                columns=["index"])

# … then use the standard videogen dataloader from
# https://github.com/lancedb/training/tree/videogen/examples/videogen
```

## Provenance

Sourced from ChronoMagic-Pro / ChronoMagic-ProH
([BestWishYsh/ChronoMagic-Pro](https://huggingface.co/datasets/BestWishYsh/ChronoMagic-Pro)),
filtered through the curation pipeline described in
[PROPOSAL.md](https://github.com/lancedb/training/blob/videogen/examples/videogen/PROPOSAL.md).

## Schema (selected columns)

{schema}
"""


def _short_schema(table) -> str:
    lines = []
    for f in table.schema:
        lines.append(f"- `{f.name}` — `{f.type}`")
    return "\n".join(lines[:30]) + ("\n…" if len(table.schema) > 30 else "")


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--db",     default="data/videos/lancedb")
    p.add_argument("--table",  required=True,
                   help="Lance table or Geneva MV name to publish.")
    p.add_argument("--repo",   required=True,
                   help="HuggingFace dataset repo, e.g. my-org/my-dataset")
    p.add_argument("--dry-run", action="store_true",
                   help="Print plan only; don't touch HF Hub.")
    p.add_argument("--private", action="store_true",
                   help="Create repo as private.")
    p.add_argument("--message", default="Upload via videogen.upload_to_hf",
                   help="Commit message.")
    args = p.parse_args(argv)

    import lancedb

    db = lancedb.connect(args.db)
    if args.table not in db.list_tables().tables:
        raise SystemExit(f"Table '{args.table}' missing in {args.db}.")
    tbl = db.open_table(args.table)
    rows = tbl.count_rows()
    table_dir = Path(args.db) / f"{args.table}.lance"
    if not table_dir.exists():
        raise SystemExit(f"Lance directory not found: {table_dir}")

    readme = _README_TEMPLATE.format(
        repo=args.repo, table=args.table, rows=rows,
        schema=_short_schema(tbl),
    )

    print(f"\n  table dir   : {table_dir}")
    print(f"  rows        : {rows:,}")
    print(f"  destination : hf://datasets/{args.repo}/data/{args.table}.lance")
    print(f"  private     : {args.private}")
    if args.dry_run:
        print("\nDry-run — README would look like:\n")
        print(readme)
        return 0

    from huggingface_hub import HfApi, create_repo

    api = HfApi()
    print(f"\nCreating repo {args.repo} (if not present) …")
    create_repo(args.repo, repo_type="dataset",
                private=args.private, exist_ok=True)

    print(f"Uploading Lance dataset directory …")
    api.upload_folder(
        folder_path=str(table_dir),
        path_in_repo=f"data/{args.table}.lance",
        repo_id=args.repo, repo_type="dataset",
        commit_message=args.message,
    )

    print(f"Uploading README …")
    api.upload_file(
        path_or_fileobj=readme.encode("utf-8"),
        path_in_repo="README.md",
        repo_id=args.repo, repo_type="dataset",
        commit_message=args.message,
    )

    print(f"\nDone — https://huggingface.co/datasets/{args.repo}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
